### ISSUE TITLE
KeyError: 'random-multiview-camera-datamodule'

### ISSUE THREAD

**Issue by anildadj** [bytedance/ImageDream#7]
**This code gives an error:**
!python3 launch.py \
    --config configs/imagedream-sd21-shading.yaml --train --gpu 0 \
    name="imagedream-sd21-shading" tag="astronaut" \
    system.prompt_processor.prompt="an astronaut jumping in air" \
    system.prompt_processor.image_path="${image_file}" \
    system.guidance.ckpt_path="${ckpt_file}" \
    system.guidance.config_path="${cfg_file}"

**Upon running the above for image to mesh conversion, it gives the following error:**

Traceback (most recent call last):
  File "/content/threestudio/launch.py", line 301, in <module>
    main(args, extras)
  File "/content/threestudio/launch.py", line 168, in main
    dm = threestudio.find(cfg.data_type)(cfg.data)
  File "/content/threestudio/threestudio/__init__.py", line 19, in find
    return __modules__[name]
**KeyError: 'random-multiview-camera-datamodule'**

**Comment by anildadj** [comment]
Please help resolve.

**Comment by raptor-wang** [comment]
haven't met this error, looks like your path of threestudio is not the one clone from ImageDream.  

you may need to use the threestudio provided in this repo.
